model_name_or_path: my_model/Qwen2.5-7B/Qwen/Qwen2.5-7B-Instruct
plot_loss: true

stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 32
lora_dropout: 0.1
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj

dataset: handcraft
template: qwen
cutoff_len: 1024
max_samples: 11952
# max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/Qwen2.5-7B/lora/sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
# max_grad_norm: 0.3 